spring: 
  profiles:
    active:
      - dev

---

spring: 
  profiles: dev #开发环境
  application: 
    name: lzp-config-dev

---
spring:
  profiles: test  #测试环境
  application:
    name: lzp-config-test

#保存为utf-8形式              